name: 自动部署 Hexo 博客

on:
  push:
    branches:
      - dev  # 只监听 dev 分支

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev

      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: 安装 Hexo
        run: npm install -g hexo-cli

      - name: 安装依赖
        run: npm install

      - name: 生成静态文件
        run: hexo generate

      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: main
          user_name: "AdventurerZzz"
          user_email: "695409304@qq.com"